### ISSUE TITLE
Add nowdoc format for auto-generated migrations

### ISSUE THREAD

**Issue by ghost** [doctrine/migrations#1388] opened 2024-01-12 13:01 UTC
### Feature Request

Add heredoc format for auto-generated migrations

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

e.g. https://github.com/doctrine/migrations/blob/3.7.x/lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php

```php
            ->addOption(
                'nowdoc',
                null,
                InputOption::VALUE_NONE,
                'Use nowdoc format for SQL statements.',
            )
```
Without the new option

```php
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE...');
    }
```
With the new option
```php
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
                CREATE TABLE...
        SQL);
    }
```

**Comment by greg0ire** [comment] 2024-01-12 13:24
Two things:

- Why not nowdoc instead? It's more consistent with `'`
- Can you elaborate on the benefits you expect to see? I know that for instance, if we use `'SQL'` as the marker, there will be better syntactic coloration with some editors, is there something else I'm missing?

**Comment by ghost** [comment] 2024-01-12 13:35
@greg0ire Yes, nowdoc too, why not 😉

Benefits
* More readable SQL statements
* More readable SQL git diffs
* Syntactic coloration
* Easier copy-paste for local testing

**Comment by greg0ire** [comment] 2024-01-12 15:05
> More readable SQL statements

How exactly would they become more readable?

> More readable SQL git diffs

This is not obvious to me either

> Easier copy-paste for local testing

Because you can copy entire lines, or for another reason?

**Comment by ghost** [comment] 2024-01-12 15:08
The `--formatted` option already does part of the job, but quote escaping makes it more difficult to read/compare.

Yes, using nowdoc or heredoc, you can copy-paste and test SQL queries without any modification (such as unescaping).

**Comment by greg0ire** [comment] 2024-01-12 15:25
TIL about `--formatted`… I guess it could indeed be nicer with NOWDOC. Now I'm not sure we should support too many scenarios. Maybe we should just switch to NOWDOC and not expose any other option. I'm curious what other maintainers think.

**Comment by ghost** [comment] 2024-01-12 23:06
@greg0ire you’re right. Nowdoc is a better choice in this case 👍

**Comment by greg0ire** [comment] 2024-01-13 10:32
@derrabus @SenseException what do you think about this change? @michael-barchy-bf would you be willing to implement it?

**Comment by michael-barchy-bf** [comment] 2024-01-19 21:34
My proposal is here https://github.com/doctrine/migrations/compare/3.7.x...michael-barchy-bf:migrations:diffcommand-nowdoc

**Comment by greg0ire** [comment] 2024-01-19 21:59
Would you mind opening a pull request? Since it's a new feature, please target 3.8.x

**Comment by ghost** [comment] 2024-01-22 17:22
Sorry, i'm not familiar with github, someone else should do it

**Comment by ghost** [comment] 2024-03-05 22:48
This issue might be a duplicate of this one : https://github.com/doctrine/migrations/issues/939

**Comment by greg0ire** [comment] 2024-03-06 07:58
Duplicate of #939

**Closed as not planned by greg0ire** 2024-03-06 07:58 UTC
