### ISSUE TITLE
Undefined Index 1 when running doctrine:migrations:migrate with autogeneretated migrations (using diff or empty generate)

### ISSUE THREAD

**Issue by Richard87** [doctrine/migrations#454] opened 2016-03-28 11:37 UTC
Hi!

I'm trying to use Doctrine/migrations-bundle with symfony but experiencing some issues. No matter what I try, I get `Undefined index 1`. I have only tried to automatically generate migrations with the `diff` command and `generate` command(trying to migrate a empty migration also fails).

Here are some logs:

	php bin\console doc:mig:mig -vvv

						Application Migrations

	WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
	Migrating up to 20160328132500 from 0
	Migration 20160328132500 failed during Pre-Checks. Error Notice: Undefined offset: 1

	  [Symfony\Component\Debug\Exception\ContextErrorException]
	  Notice: Undefined offset: 1

	Exception trace:
	 () at .\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:98
	 Symfony\Component\Debug\ErrorHandler->handleError() at .\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:98
	 Zend\Code\Generator\MethodGenerator::clearBodyIndention() at .\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:77
	 Zend\Code\Generator\MethodGenerator::fromReflection() at .\vendor\ocramius\proxy-manager\src\ProxyManager\Generator\MethodGenerator.php:39
	 ProxyManager\Generator\MethodGenerator::fromReflection() at .\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingMethodInter
	ceptor.php:48
	 ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingMethodInterceptor::generateMethod() at .\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\Lazy
	LoadingValueHolderGenerator.php:118
	 ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->ProxyManager\ProxyGenerator\{closure}() at n/a:n/a
	 array_map() at .\vendor\ocramius\proxy-manager\src\ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator.php:90
	 ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate() at .\vendor\ocramius\proxy-manager\src\ProxyManager\Factory\AbstractBaseFactory.php:119
	 ProxyManager\Factory\AbstractBaseFactory->generateProxyClass() at .\vendor\ocramius\proxy-manager\src\ProxyManager\Factory\AbstractBaseFactory.php:82
	 ProxyManager\Factory\AbstractBaseFactory->generateProxy() at .\vendor\ocramius\proxy-manager\src\ProxyManager\Factory\LazyLoadingValueHolderFactory.php:45
	 ProxyManager\Factory\LazyLoadingValueHolderFactory->createProxy() at .\vendor\doctrine\migrations\lib\Doctrine\DBAL\Migrations\Provider\LazySchemaDiffProvider.php:66
	 Doctrine\DBAL\Migrations\Provider\LazySchemaDiffProvider->createFromSchema() at .\vendor\doctrine\migrations\lib\Doctrine\DBAL\Migrations\Version.php:277
	 Doctrine\DBAL\Migrations\Version->execute() at .\vendor\doctrine\migrations\lib\Doctrine\DBAL\Migrations\Migration.php:176
	 Doctrine\DBAL\Migrations\Migration->migrate() at .\vendor\doctrine\migrations\lib\Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand.php:143
	 Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand->execute() at .\vendor\doctrine\doctrine-migrations-bundle\Command\MigrationsMigrateDoctrineCommand.php:54
	 Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() at .\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:256
	 Symfony\Component\Console\Command\Command->run() at .\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:807
	 Symfony\Component\Console\Application->doRunCommand() at .\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:186
	 Symfony\Component\Console\Application->doRun() at .\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:80
	 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at .\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:117
	 Symfony\Component\Console\Application->run() at .\bin\console:29

	doctrine:migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-
	q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

Some stats:

	php bin\console doc:mig:stat

	 == Configuration

		>> Name:                                               Application Migrations
		>> Database Driver:                                    pdo_mysql
		>> Database Name:                                      eportal
		>> Configuration Source:                               manually configured
		>> Version Table Name:                                 migration_versions
		>> Version Column Name:                                version
		>> Migrations Namespace:                               Application\Migrations
		>> Migrations Directory:                               .\app/DoctrineMigrations
		>> Previous Version:                                   Already at first version
		>> Current Version:                                    0
		>> Next Version:                                       2016-03-28 13:25:00 (20160328132500)
		>> Latest Version:                                     2016-03-28 13:25:00 (20160328132500)
		>> Executed Migrations:                                0
		>> Executed Unavailable Migrations:                    0
		>> Available Migrations:                               1
		>> New Migrations:                                     1

And the migration script this test was executing:

	<?php

	namespace Application\Migrations;

	use Doctrine\DBAL\Migrations\AbstractMigration;
	use Doctrine\DBAL\Schema\Schema;

	/**
	 * Auto-generated Migration: Please modify to your needs!
	 */
	class Version20160328132500 extends AbstractMigration
	{
		/**
		 * @param Schema $schema
		 */
		public function up(Schema $schema)
		{
			// this up() migration is auto-generated, please modify it to your needs

		}

		/**
		 * @param Schema $schema
		 */
		public function down(Schema $schema)
		{
			// this down() migration is auto-generated, please modify it to your needs

		}
	}

Also tested this script with the same result:

	<?php

	namespace Application\Migrations;

	use Doctrine\DBAL\Migrations\AbstractMigration;
	use Doctrine\DBAL\Schema\Schema;

	/**
	 * Auto-generated Migration: Please modify to your needs!
	 */
	class Version20160328133654 extends AbstractMigration
	{
		/**
		 * @param Schema $schema
		 */
		public function up(Schema $schema)
		{
			// this up() migration is auto-generated, please modify it to your needs
			$this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

			$this->addSql('CREATE TABLE user_groups (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, group_id INT DEFAULT NULL, INDEX IDX_953F224DA76ED395 (user_id), INDEX IDX_953F224DFE54D947 (group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
			$this->addSql('CREATE TABLE user_meetings (id INT AUTO_INCREMENT NOT NULL, meeting_id INT DEFAULT NULL, user_id INT DEFAULT NULL, attended TINYINT(1) NOT NULL, INDEX IDX_A473B6E267433D9C (meeting_id), INDEX IDX_A473B6E2A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
			$this->addSql('ALTER TABLE user_groups ADD CONSTRAINT FK_953F224DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
			$this->addSql('ALTER TABLE user_groups ADD CONSTRAINT FK_953F224DFE54D947 FOREIGN KEY (group_id) REFERENCES groups (id)');
			$this->addSql('ALTER TABLE user_meetings ADD CONSTRAINT FK_A473B6E267433D9C FOREIGN KEY (meeting_id) REFERENCES meeting (id) ON DELETE CASCADE');
			$this->addSql('ALTER TABLE user_meetings ADD CONSTRAINT FK_A473B6E2A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
		}

		/**
		 * @param Schema $schema
		 */
		public function down(Schema $schema)
		{
			// this down() migration is auto-generated, please modify it to your needs
			$this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

			$this->addSql('DROP TABLE user_groups');
			$this->addSql('DROP TABLE user_meetings');
		}
	}

**Comment by Richard87** [comment] 2016-03-28 12:39
So it worked flawlessly on production (CentOs 7), but not in development (Win10).. I'll keep testing

**Comment by mikeSimonson** [comment] 2016-03-28 13:41
Sadly this is a known issue with windows in one of our dependency.
I am doing all I can to have it fixed but its the holidays and stuff.

It's a duplicate of https://github.com/doctrine/DoctrineMigrationsBundle/issues/154

**Comment by mikeSimonson** [comment] 2016-03-28 13:44
You can probably fix it by doing.

``composer require ocramius/proxy-manager ^1.0``

This will fix the version of the dependency of proxy manager that has the issue to a version were the issue is not present.

**Comment by Richard87** [comment] 2016-03-28 14:03
Ofcourse, please take a vacation ;)  Thanks for explaining though...

**Comment by Richard87** [comment] 2016-03-28 14:11
Fore your information (whenever you're back from vacation ;) )

Changing `MethodReflection:231` from `"\n"` to `PHP_EOL` solved the issue on my first test, no idea what other files uses this tho :P

**Comment by chrisguitarguy** [comment] 2016-07-06 20:42
This can probably be closed since the issue is fixed in zend-code.

**Comment by mikeSimonson** [comment] 2016-07-06 20:43
@chrisguitarguy Yes I just forgot to close it.

**Closed by mikeSimonson** 2016-07-06 20:43 UTC
