### ISSUE TITLE
Migration mismatch detection

### ISSUE THREAD

**Issue by petrknap** [doctrine/migrations#1036] opened 2020-07-09 13:00 UTC
|    Q        |   A
|------------ | -----
| Version     | 2.2.1

### Support Question

Where is the right place to implement migration mismatch detection? I need place where I can get list of all migrations on the hard-drive and list of all applied migrations from DB and where I can stop it by single Exception.

#### Problem

When more developers works on the same project simultaneously, then they have multiple branches and nobody know which migration will be merged and executed first. **Newer migration is executed before older migration** when older migration is merged after newer migration.

```
                                                              
                    Application Migrations                    
                                                              

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20200709121503 from 20200709121503

  ++ migrating 20160709121528

Migration 20160709121528 was executed but did not result in any SQL statements.

  ++ migrated (took 128.5ms, used 16M memory)

  ------------------------

  ++ finished in 140.5ms
  ++ used 16M memory
  ++ 1 migrations executed
  ++ 0 sql queries
```

As you can see there is any warning, it simply executes 2016 migration after 2020 migration. My solution is here https://github.com/petrknap/php-migrationtool/blob/master/src/AbstractMigrationTool.php#L111 and I wish to add it to doctrine/migrations too.

**Comment by goetas** [comment] 2020-07-13 09:50
To be honest I think that this is not a problem of the migration library (and neither of the code in your project). 
In my opinion the problem is in your branching/merging strategy. 
What you could try to do, is to add a test in your CI/CD pipeline, and check that the added migrations should have a date higher than the one that are already present. 

In this way you detect the failure even before the code lands in your main branches. If the migration with an unexpected timestamp has been already merged, it might be too late.

**Closed by goetas** 2020-07-13 09:50 UTC

**Comment by petrknap** [comment] 2020-07-13 14:06
Then why there is mechanism for detection of missing migration? Isn't this the same kind of problem?

```
                                                              
                    Application Migrations                    
                                                              

WARNING! You have 1 previously executed migrations in the database that are not registered migrations.
    >> 2020-07-13 14:03:51 (20200713140351)
Are you sure you wish to continue? (y/n)n
Migration cancelled!
```

**Comment by goetas** [comment] 2020-07-13 14:42
A missing migration is a migration that has been executed, and now suddenly the code is not there anymore. 
If that migration allowed to revert its changes (with `down()`), not it is not possible anymore (it might  lead to errors as another migration might be depending on the `down()` of that migration that is not there anymore ). 

In your case, is just a matter of order of execution, not on "did the migration ever exist?"
