### ISSUE TITLE
DDL migrations produce errors on PHP 8.0 + MySQL in transactional mode

### ISSUE THREAD

**Issue by lippok** [doctrine/migrations#1104] opened 2020-12-25 08:24 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.2 (probably > 3.0)
| PHP     | 8.0
| DBAL-Driver     | PDO
| DB     | mysql 5.7 and 8.0

#### Summary

When running the command `migrations:migrate` with a ddl sql statement (e.g. `create table`) on php 8.0 I got an error:

> In Connection.php line 1761: There is no active transaction  

#### Previous behavior
Bevore php 8.0 the migration produces no errors.

#### Current behavior
DDL statements on mysql result in an implicit commit (see [mysql documentation](https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html)). This causes the [explicit commit](https://github.com/doctrine/migrations/blob/3.0.2/lib/Doctrine/Migrations/Version/DbalExecutor.php#L215) in transactional mode to fail. But only starting with php 8.0 an error is raised (probably due to php/php-src@990bb34).

To bypass the error I can disable the transactional mode by overwriting ``isTransactional`` in my migration, but in my opinion it's a breaking change in the behaviour when using php 8.

I found the same issue in a bug report for the yii framework (yiisoft/yii2#18406) that helped me to figure out what happens. They fixed it by checking [`PDO::inTransaction`](https://www.php.net/manual/de/pdo.intransaction.php) before running the commit. If I'm not wrong this method is not wrapped by the dbal package and therefore not available here.

#### How to reproduce

1. Create a migration with a ddl statement.
1. Let the transactional mode active.
1. Run the migration.

**Comment by chriskapp** [comment] 2020-12-26 15:55
It looks like this problem exists also at version `2.3.2`. This occurred on our CI server, we are using Mysql and PHP 8:

```
Fatal error: Uncaught PDOException: There is no active transaction in /home/travis/build/apioo/fusio-impl/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1761
PDOException: There is no active transaction in /home/travis/build/apioo/fusio-impl/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1761
Call Stack:
    0.0001     414648   1. {main}() /home/travis/build/apioo/fusio-impl/vendor/phpunit/phpunit/phpunit:0
    0.0050    1361800   2. PHPUnit\TextUI\Command::main($exit = ???) /home/travis/build/apioo/fusio-impl/vendor/phpunit/phpunit/phpunit:61
    0.0050    1361928   3. PHPUnit\TextUI\Command->run($argv = [0 => 'vendor/bin/phpunit'], $exit = TRUE) /home/travis/build/apioo/fusio-impl/vendor/phpunit/phpunit/src/TextUI/Command.php:163
    0.0050    1361928   4. PHPUnit\TextUI\Command->handleArguments($argv = [0 => 'vendor/bin/phpunit']) /home/travis/build/apioo/fusio-impl/vendor/phpunit/phpunit/src/TextUI/Command.php:171
    0.0082    1553328   5. PHPUnit\TextUI\Command->handleBootstrap($filename = '/home/travis/build/apioo/fusio-impl/tests/bootstrap.php') /home/travis/build/apioo/fusio-impl/vendor/phpunit/phpunit/src/TextUI/Command.php:891
    0.0083    1559400   6. PHPUnit\Util\FileLoader::checkAndLoad($filename = '/home/travis/build/apioo/fusio-impl/tests/bootstrap.php') /home/travis/build/apioo/fusio-impl/vendor/phpunit/phpunit/src/TextUI/Command.php:1095
    0.0083    1559640   7. PHPUnit\Util\FileLoader::load($filename = '/home/travis/build/apioo/fusio-impl/tests/bootstrap.php') /home/travis/build/apioo/fusio-impl/vendor/phpunit/phpunit/src/Util/FileLoader.php:47
    0.0083    1563256   8. include_once('/home/travis/build/apioo/fusio-impl/tests/bootstrap.php') /home/travis/build/apioo/fusio-impl/vendor/phpunit/phpunit/src/Util/FileLoader.php:59
    0.0209    3591400   9. runMigrations() /home/travis/build/apioo/fusio-impl/tests/bootstrap.php:9
    0.0271    4526616  10. Doctrine\Migrations\Migrator->migrate($to = ???, $migratorConfiguration = ???) /home/travis/build/apioo/fusio-impl/tests/bootstrap.php:18
    0.0503    5141448  11. Doctrine\Migrations\Migrator->executeMigration($migrationsToExecute = [20200905081453 => class Doctrine\Migrations\Version\Version { private $configuration = class Doctrine\Migrations\Configuration\Configuration { ... }; private $outputWriter = class Doctrine\Migrations\OutputWriter { ... }; private $version = '20200905081453'; private $migration = class Fusio\Impl\Migrations\Version\Version20200905081453 { ... }; private $connection = class Doctrine\DBAL\Connection { ... }; private $class = 'Fusio\\Impl\\Migrations\\Version\\Version20200905081453'; private $state = 3; private $versionExecutor = class Doctrine\Migrations\Version\Executor { ... } }, 20200905191429 => class Doctrine\Migrations\Version\Version { private $configuration = class Doctrine\Migrations\Configuration\Configuration { ... }; private $outputWriter = class Doctrine\Migrations\OutputWriter { ... }; private $version = '20200905191429'; private $migration = class Fusio\Impl\Migrations\Version\Version20200905191429 { ... }; private $connection = class Doctrine\DBAL\Connection { ... }; private $class = 'Fusio\\Impl\\Migrations\\Version\\Version20200905191429'; private $state = 0; private $versionExecutor = class Doctrine\Migrations\Version\Executor { ... } }, 20200905191956 => class Doctrine\Migrations\Version\Version { private $configuration = class Doctrine\Migrations\Configuration\Configuration { ... }; private $outputWriter = class Doctrine\Migrations\OutputWriter { ... }; private $version = '20200905191956'; private $migration = class Fusio\Impl\Migrations\Version\Version20200905191956 { ... }; private $connection = class Doctrine\DBAL\Connection { ... }; private $class = 'Fusio\\Impl\\Migrations\\Version\\Version20200905191956'; private $state = 0; private $versionExecutor = class Doctrine\Migrations\Version\Executor { ... } }], $direction = 'up', $migratorConfiguration = class Doctrine\Migrations\MigratorConfiguration { private $dryRun = FALSE; private $timeAllQueries = FALSE; private $noMigrationException = FALSE; private $allOrNothing = FALSE; private $fromSchema = NULL }) /home/travis/build/apioo/fusio-impl/vendor/doctrine/migrations/lib/Doctrine/Migrations/Migrator.php:148
```

**Comment by nicklog** [comment] 2020-12-31 11:20
Just do it like pierres as a workaround until its fixed.
Add following code into your migrations.

```php
class Version**** extends AbstractMigration
{

    public function up(Schema $schema): void
    {
        // your migration
    }

    public function isTransactional(): bool
    {
        return false;
    }
}
```

**Comment by greg0ire** [comment] 2021-01-07 14:55
I'm wondering if this issue should be moved to `doctrine/dbal` instead. It would make sense since the solution will mean dealing with a specifics of a particular platform. This could be done in a generic way though, with `PDO::inTransaction()`, as pointed out by OP.

@morozov , what do you think? Should this be handled in `Connection::commit()`?

**Comment by lippok** [comment] 2021-01-07 14:59
An other option would be to catch the error [here where he is thrown](https://github.com/doctrine/migrations/blob/3.0.2/lib/Doctrine/Migrations/Version/DbalExecutor.php#L215).

**Comment by greg0ire** [comment] 2021-01-07 15:04
I think that's an anti-pattern (at least in PHP, I think in python it would be… well pythonic). IIRC that's because exceptions are costly but I'm not sure this is true, it might be cultural. Anyway, it's not something that we usually do I think.

Also, `doctrine/migrations` might not be the only package sending DDL statements through the DBAL, so I think it would make sense to handle this there.

**Comment by morozov** [comment] 2021-01-07 19:17
@greg0ire as far as I understand, it's the migrations who starts the transaction, executes the DDL and then commits the transaction that already has been implicitly committed. Why and how should the DBAL solve this problem?

**Comment by greg0ire** [comment] 2021-01-07 19:27
> it's the migrations who starts the transaction

I did not spot this, and of course, you're correct. This issue is in the right repository 👍

**Comment by greg0ire** [comment] 2021-01-07 19:34
I believe the fix could be a simple

```diff
-if ($migration->isTransactional()) {
+if ($migration->isTransactional() && (!$this->connection->getWrappedConnection() instanceof PDOConnection || $this->connection->getWrappedConnection()->inTransaction())) {
```

Can anybody try that?

**Comment by lippok** [comment] 2021-01-08 06:28
I had to add `use Doctrine\DBAL\Driver\PDOConnection;`, afterwards your patch works! `PDOConnection` is marked as deprecated but I assume only for external use and it's ok to use it here.

**Comment by greg0ire** [comment] 2021-01-08 07:53
A way to do the same without resorting to a deprecated name would be to use `PDO` instead of `PDOConnection`, since `PDOConnection extends PDO`.

**Comment by lippok** [comment] 2021-01-08 07:58
Yes, `instanceof \PDO` is also working, just checked it. I think this approach is better.

**Comment by greg0ire** [comment] 2021-01-08 08:20
@morozov I am not sure the DBAL could solve the issue, but it would definitely help to have `inTransaction()` added to the API of `Connection`. For systems that don't have an equivalent to `PDO::inTransaction()`, it could still be implemented by doing some bookkeeping regarding the number of calls to `beginTransaction()`, `commit()` and `rollBack()`.

In v2, this package has 4 occurrences of `commit()`, all of which probably need to be complexified to account for this MySQL "feature". Also, there are 4 occurrences of `rollBack()`, and surely, calling `rollBack()` if there is no active transaction would fail, e.g. in this (unlikely, I concede that) scenario:

```php
try {
    $connection->beginTransaction();
    $connection->executeSomeSQLWithDDLStatements(); // works fine and auto-commits
    callUnrelatedToDatabaseThatThrows();
} catch (Throwable $e) {
    $connection->rollBack();
}
```

Alternate solution to adding `inTransaction` to the API would be to add an argument to `commit` and `rollBack` that would make the check to `inTransaction` implicit, or to add a new API like `maybeCommit` / `maybeRollback`.

All of my proposals would constitue BC-breaks in the DBAL though, so we would still have to complexify code here as a first step I'm afraid.

Also, none of them feel really good to me, maybe you will have better ideas?

**Comment by morozov** [comment] 2021-01-08 19:36
> I believe the fix could be a simple
> 
> ```diff
> -if ($migration->isTransactional()) {
> +if ($migration->isTransactional() && (!$this->connection->getWrappedConnection() instanceof PDOConnection || $this->connection->getWrappedConnection()->inTransaction())) {
> ```

Should it work with the non-PDO MySQL driver as well and only with the MySQL (PDO and non-PDO) drivers?

**Comment by greg0ire** [comment] 2021-01-08 20:11
I overlooked mysqli, and the link to php-src given by @lippok  above points to a change that is about mysqli and only it, so that's weird. It does mean my fix is probaby incomplete, the condition should be complexify to handle mysqli too.

**Comment by Wirone** [comment] 2021-01-08 22:58
On the other hand `inTransaction()` could be introduced on interface's level and:
- each driver could provide `bool` result based on native code (PDO) or internal data
- return type could be `?bool` where `null` could represent unknown state, to be handled differently per driver. This isn't state of the art solution but could be good enough for some transitional period.

I hit this issue too when upgraded to PHP8, right now I've used workaround with custom abstract migration class with @nicklog's `isTransactional()` returning always `false`. So basically I've added one layer of inheritance but thanks to that I just changed extended class in every migration file (instead of adding `isTransactional()` everywhere) and changed my migration template so my abstract class will be used in new migrations. When transaction support will be delivered, I will just change `isTransactional()` in abstract migration.

**Comment by derrabus** [comment] 2021-01-08 23:45
Does mysqli complain if you COMMIT without an active transaction? I thought this was a PDO thing.

**Comment by greg0ire** [comment] 2021-01-11 08:09
I thought so too, but OP linked to a commit that seems to be about mysqli (https://github.com/php/php-src/commit/990bb34) @lippok, or any of the 15 people that upvoted this, please try with mysqli and report back.

**Comment by lippok** [comment] 2021-01-11 11:09
When I'm using the driver `mysqli` instead of `pdo_mysql`, I cannot reproduce the transaction error at all. `mysqli` seems not to be affected but I don't understand why. Unfortunately I am not familiar with this project, thus I don't know which code is executed instead of the [`DbalExecutor`](https://github.com/doctrine/migrations/blob/3.0.2/lib/Doctrine/Migrations/Version/DbalExecutor.php). 

I assume it has no influence, but I pass the db configuration with the option `--db-configuration <configfile>`.

**Comment by greg0ire** [comment] 2021-01-11 12:40
Furthermore, we can see that https://github.com/php/php-src/commit/990bb34 is also included in 7.4.13, so we probably would have had a lot of bug reports if there was an issue with mysqli indeed.

**Comment by morozov** [comment] 2021-01-12 03:55
> […] maybe you will have better ideas?

What are the expectation of the users who use transactional migrations and MySQL that doesn't respect them?

**Comment by greg0ire** [comment] 2021-01-12 07:52
Here, it's not end users that are asking for transactions, it's this package. Maybe not using transactions when MySQL is detected would be the best solution. We could fix this by having `AbstractMigration::isTransactional` return `false` in that case, which would make sense, because in the context of migrations, can we really call MySQL a transactional RDBMS when it behaves this badly with migrations?

**Comment by morozov** [comment] 2021-01-12 16:54
This way, the behavior of the migration is not portable. If the user runs it on say PostgreSQL and MySQL, they will have to be prepared that the migration won't be transactional in the worst case. Then what's the point in having it transactional with PostgreSQL? IMO, it's the party who builds and runs the migration that needs to decide whether it has to be transactional or not. If it has to be transactional, it cannot be run on MySQL.

**Comment by greg0ire** [comment] 2021-01-12 22:44
Sounds fair. This means:
- we should throw an exception with a helpful message in case there is an attempt to run a transactional migration under circumstances that we will lead to a crash (I gather it's PHP 8 + `pdo_mysql`?)
- we might complexify `AbstractMigration::isTransactional()` to have saner defaults in that case, so that people using MySQL don't have to always override that method. Alternatively, we may tweak the migration generator so that it generates the override in that case, but I feel the first solution is better.

**Comment by morozov** [comment] 2021-01-12 23:13
> we should throw an exception with a helpful message in case there is an attempt to run a transactional migration under circumstances that we will lead to a crash (I gather it's PHP 8 + `pdo_mysql`?)

Since it's the MySQL platform that doesn't support DDL in a transaction, why should the logic above depend on the PHP version and the driver?

**Comment by derrabus** [comment] 2021-01-12 23:48
Keep in mind that a migration does not necessarily contain DDL statements. A migration that only consists of `INSERT` and `UPDATE` statements can very well be transactional.

**Comment by greg0ire** [comment] 2021-01-13 07:11
@morozov because apparently the issue is swept under the rug when using other configurations. If we make the condition based on the platform, then we will make a lot more migrations that could run properly with the expected outcome no longer valid.

@derrabus ' remark makes me think that even this would not be possible, and that the only thing we can improve is the defaults, if we think the migrations he describes are the exception rather than the rule.

**Comment by stof** [comment] 2021-01-13 07:34
The issue I see is that disabling transactional behavior requires editing each generated migration. That would be painful for MySQL project. It would at least require a config setting to be able to generate non-transactional migrations by default (or disable transactional with a separate rule)

**Comment by greg0ire** [comment] 2021-01-13 07:45
@stof that's what I proposed here, along with another solution:

> we might complexify AbstractMigration::isTransactional() to have saner defaults in that case, so that people using MySQL don't have to always override that method. Alternatively, we may tweak the migration generator so that it generates the override in that case, but I feel the first solution is better.

What's your opinion on the first solution? Too risky? It does change the behavior existing migrations, and would technically be a BC-break for that reason I suppose, although one could argue that the behavior was not the expected one in the first place.

**Comment by stof** [comment] 2021-01-13 11:10
@greg0ire that first solution would still require my proposal if you don't want mysql users to hate the Doctrine maintainers by having to edit manually 100% of generated migrations to make them work.

**Comment by stof** [comment] 2021-01-13 11:13
> What's your opinion on the first solution? Too risky? It does change the behavior existing migrations, and would technically be a BC-break for that reason I suppose, although one could argue that the behavior was not the expected one in the first place.

I would propose to have `AbstractMigration::isTransactional()` defaulting to `$platform->supportsTransactionalDDL()` (adding that method in DBAL if it does not exist yet).

For platforms supporting transactional DDL, this is the best default (if you make a mistake in your migration, it avoids having to clean a state of a half-executed migration). But default to always transactional indeed does not look good anymore on mysql due to the magic it does...

**Comment by greg0ire** [comment] 2021-01-13 12:32
Fully agree with your second comment, but I don't understand the first one: if we do what you describe in your second comment, `isTransactional()` will be inherited to all existing migrations, which means there will be nothing to edit manually, will there be?

**Comment by greg0ire** [comment] 2021-01-14 12:55
> I would propose to have AbstractMigration::isTransactional() defaulting to $platform->supportsTransactionalDDL() (adding that method in DBAL if it does not exist yet).

That method does not exist, and I just wrote it in a branch on my local repository, only to realize there is no 2.13 branch yet and such a new feature is supposed to go to 3.1 (since it's a new feature), which this package is not even allowing yet. I think we will probably resort to an `instanceof` check on the platform directly in this package instead.

**Comment by greg0ire** [comment] 2021-01-14 12:59
Link to the 3.1 PR in case anyone is interested: https://github.com/doctrine/dbal/pull/4481

**Comment by alexandre-leng** [comment] 2021-01-25 13:30
i have the same issue

```
[notice] Migrating up to DoctrineMigrations\Version20210125113154

In Connection.php line 1761:

  There is no active transaction  
```
Symfony LOG
[dev.log](https://github.com/doctrine/migrations/files/5866769/dev.log)

i try on XAMP with php 8.0.1 and still i get the bug
and i try on MAMP with php  7.4.1 and i still get the same bug

Other dev on the web  have the same problem
ENGLISH
https://www.gitmemory.com/issue/doctrine/migrations/1104/757051253

FRENCH
https://openclassrooms.com/forum/sujet/soucis-symphony-5-2-et-php-8-0-1

ANOTHER BUG RELATED TO
https://github.com/yiisoft/yii2/issues/18406

**Comment by albe** [comment] 2021-02-25 23:55
So AFAIS up to PHP 7.4 such a migration will execute roughly as if it were `isTransactional() == false` (only roughly because everything up to the first DDL will be within a transaction), because the failing commit was silently ignored. In PHP8 however the manual commit will now throw a PDOException, which totally breaks the transaction and stops following migrations in the execution plan from running. This is a major PITA for all projects using doctrine migrations and trying to support PHP 8, as it can not easily be handled by them automatically (catching the exception there will still have later migrations not executed). This means all existing migrations need to be changed and own users need to be advised to change their migrations.

In this case, I'm with the OP and the right solution IMO would be to create a BUGFIX that catches this very specific PDOException and ignores it to create b/c for now. Then a "sane" solution to solve this through proper API can be discussed with all the time needed.

```php
        if ($migration->isTransactional()) {
            //commit only if running in transactional mode
            try {
                $this->connection->commit();
            } catch (\PDOException $e) {
                // FIXME: Workaround for PHP 8 and PDO mysql b/c, see https://github.com/doctrine/migrations/issues/1104
                if (PHP_MAJOR_VERSION < 8 || $e->getMessage() !== 'There is no active transaction') {
                    throw $e;
                }
            }
        }
```
Is this an anti-pattern? Pretty sure. Would I want to do something like this regularly? Nope. Is this solving a pain? Yep. Dirty as heck, but it is what it is.

**Comment by bpolaszek** [comment] 2021-02-26 06:22
> Is this an anti-pattern? Pretty sure. Would I want to do something like this regularly? Nope. Is this solving a pain? Yep. Dirty as heck, but it is what it is.

It's ugly, but I like it! 👍

**Comment by imreg** [comment] 2021-03-11 17:26
**The error still exists:**

When package: "**doctrine/migrations": "^3.1.0**",

`Cannot load Xdebug - it was already loaded
**PHP 8.0.2 (cli) (built: Feb  5 2021 04:12:54) ( NTS )**
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
user@6ff7b32a5315:/var/www/html/frontend$ bin/console doctrine:migrations:migrate --no-interaction --all-or-nothing
Cannot load Xdebug - it was already loaded
[notice] Migrating up to DoctrineMigrations\Version20210311154750

In Connection.php line 1761:
                                  
  **There is no active transaction**  
                                  

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]
`

**Comment by ostrolucky** [comment] 2021-03-11 23:48
Another workaround is to switch to `mysqli` driver instead of `pdo_mysql`, as only `pdo_mysql` triggers this exception, as can be seen in https://github.com/doctrine/dbal/pull/4544

**Comment by greg0ire** [comment] 2021-03-13 17:03
@albe I think people already have found some reasonable workarounds IMO, see https://github.com/doctrine/migrations/issues/1104#issuecomment-757039024 for instance. There is no rush.

@imreg why would the issue no longer exist? The issue is still open. I'm hiding your answer as duplicate (of the original issue).


I think a good first step towards fixing this would be to add a configuration option defaulting to `true` and governing what is returned here: https://github.com/doctrine/migrations/blob/34b4f7fa0f8c1385d531841b1d451b736efcd9b0/lib/Doctrine/Migrations/AbstractMigration.php#L59-L62

That way, if the user wants to switch from PostgreSQL to MySQL, they can decide whether they want to keep using `true` or `false` depending on whether they mostly migrate their schema or their data. That option could be named `transactional_by_default`

**Comment by ostrolucky** [comment] 2021-03-13 17:15
I have different opinion. Even though it's dirty, I think we need to go with https://github.com/doctrine/migrations/issues/1104#issuecomment-786311346 until it's fixed in DBAL. We shouldn't default to false even in MySQL, because migrations don't have to contain DDL changes only. Sometimes they contain things like data inserts or update only. MySQL transactions work perfectly fine there. This is why checking for platform, or changing some variable applicable for all transactions in project globally is not enough. We should keep defaulting to transactions whenever is it possible. But we don't know if user is doing DDL changes in particular transaction or not, that's why we have to still go through transaction, catch this particular error and ignore it.

**Comment by greg0ire** [comment] 2021-03-13 17:37
> until it's fixed in DBAL

Given the answer you got [here](https://github.com/doctrine/dbal/pull/4544#discussion_r593550022), I'm starting to have some doubts about this.

Regarding https://github.com/doctrine/migrations/issues/1104#issuecomment-786311346 , it has the merit of not being coupled at all to the DBAL, unlike `instanceof MySQLPlatform`, so there's that. What's very wrong with it is that it hides the fact that the migration is not wrapped in a transaction to our users and that despite the fact `isTransactional()` returns `true`. That has always been the case, and it's only surfacing now that an exception is thrown, but that kind of shushing sure doesn't feel right. 

Maybe it should be part of the configuration? Meaning possible values for `transactional_by_default` could become:
- `true`
- `tentatively` or `mostly` or `silence_failures`
- `false`

That way people that use MySQL + PDO or Oracle or whatever doesn't work can have migrations that works without deluding themselves. We could even print a message in the output indicating whether the migration ended up being transactional or not in this kind of case.

**Comment by albe** [comment] 2021-03-13 17:50
> Maybe it should be part of the configuration? Meaning possible values for transactional_by_default could become:
> 
> * true
> * tentatively or mostly or silence_failures
> * false
>
>That way people that use MySQL + PDO or Oracle or whatever doesn't work can have migrations that works without deluding > themselves. We could even print a message in the output indicating whether the migration ended up being transactional or not in this kind of case.

Don't get me wrong. That sounds totally sensible and I like that idea. But that is still breaking for existing migrations/code and rather a new feature than a bugfix. I still think existing expectations on the behaviour should be kept up first through a patch level fix, then be dealt with new behaviour in a new minor version (at which point the dirty patch can be reverted again).

**Comment by ostrolucky** [comment] 2021-03-13 17:52
Yeah one thing after another. People were delusioned for a long long time that they get some kind of transaction protection during DDL statements in MySQL, this is not the right ticket to solve it in. By the way, Oracle also doesn't support it and possibly other databases. For now we just need to make migrations work with MySQL again. That's why I plan to submit a patch today or tomorrow according solution in  https://github.com/doctrine/migrations/issues/1104#issuecomment-786311346 so we could already have fix which makes migrations on PHP 8 with most popular RDBMS work again.

**Comment by albe** [comment] 2021-03-13 18:20
> @albe I think people already have found some reasonable workarounds IMO, see [#1104 (comment)](https://github.com/doctrine/migrations/issues/1104#issuecomment-757039024) for instance. There is no rush.

Unfortunately, for us this is not possible. We have a [Framework](https://github.com/neos/flow-development-collection) that relies on [Doctrine migrations](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Migrations/Mysql/Version20200908155620.php) and our consumers all have built own migrations based on their application code. While we could create an intermediary layer for the framework level migrations, we would need to also change all those custom migration classes and without that they can not upgrade to PHP 8. Also, even if we introduce this intermediary layer and somehow update all those migrations through a code migration, would we need to remove that layer again at some point, because it becomes an empty class?

**Comment by greg0ire** [comment] 2021-03-13 19:08
I see. If we are going to do this I think we should also fix [this paragraph of the docs](https://www.doctrine-project.org/projects/doctrine-migrations/en/3.1/reference/migration-classes.html#istransactional). We should probably add a warning similar to [this one](https://www.doctrine-project.org/projects/doctrine-migrations/en/3.1/reference/configuration.html#all-or-nothing-transaction) (but in proper english :wink:), and tell people to refer to the docs of their RDBMS to know what might actually be happening.

**Comment by greg0ire** [comment] 2021-03-13 20:06
Since that documentation issue already exists for PHP < 8, I made a PR for that: https://github.com/doctrine/migrations/pull/1130

**Comment by ostrolucky** [comment] 2021-03-13 21:07
And I have opened https://github.com/doctrine/migrations/pull/1131 for fixing PHP 8.0 + MySQL issue.

**Closed as completed** 2021-03-14 11:13 UTC
Labels: Bug

**Comment by abbul** [comment] 2021-04-05 18:39
Hi. I had the same error, and this worked for me:

```
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

    all_or_nothing: true
```

**Comment by Zempheroth** [comment] 2021-04-06 08:46
any fixes for php 8?
weird things but `all_or_nothing` doesn't help
still using `isTransactional()`  return false

**Comment by greg0ire** [comment] 2021-04-06 09:09
@Zempheroth yes there has been a fix, that is why the issue is closed.

**Comment by yyaremenko** [comment] 2021-06-01 09:46
I am still getting this error. Are you sure the bug was actually fixed?

**Comment by Lwackp** [comment] 2021-06-01 12:16
I added this requirement in my composer.json to get the fix:
```
"doctrine/migrations": "^2.3.3",
```

**Comment by yyaremenko** [comment] 2021-06-01 18:14
well that's even more weird, as in ```composer.json``` I have
```
...
"doctrine/doctrine-migrations-bundle": "^3.0",
...
```
and in ```composer.lock``` I see that ```doctrine-migrations-bundle``` bundle requires literally
```
...
"doctrine/migrations": "~3.0",
...
```
and so, in ```composer.lock``` I also have
```
...
"name": "doctrine/migrations",
"version": "3.0.2",
...
```
so should I assume the bugfix was not imported into v3.* yet?...

**Comment by azjezz** [comment] 2021-06-01 20:06
it's out in 3.1.1, and 2.3.3.

If you are using doctrine migrations 2, run the following:

```
composer require doctrine/migrations:^2.3.3
```

If you are using doctrine migrations 3, run the following:
```
composer require doctrine/migrations:^3.1.1
```

**Comment by Zempheroth** [comment] 2021-06-02 07:47
It sounds bad, but yesterday two things are happened:
- I've received some notifications from this thread and was strongly surprised WHY(because problem was solved and all was fine for at least last 1+month)
- at the evening the problem came back due deploy project to AWS

And now I'm again seeing `There is no active transaction` error for migrations without `isTransactional() return false`

>   "doctrine/doctrine-migrations-bundle": "^3.0", ( that are cause installing 3.1 version also)

**Comment by Zempheroth** [comment] 2021-06-02 08:12
@greg0ire any ideas?

**Comment by yyaremenko** [comment] 2021-06-02 13:37
@Lwackp @azjezz thank you guys for help

@Zempheroth this fixed the problem for me:

[UPD]
```
composer update doctrine/migrations && composer require doctrine/doctrine-migrations-bundle:^3.1.1
```
@greg0ire It might have sense to update [Doctrine Migrations Bundle doc](https://github.com/doctrine/DoctrineMigrationsBundle/blob/3.1.x/README.markdown) so that it would reference v3.1 not v3.0

**Comment by stingus** [comment] 2021-06-02 13:47
> 2. Remove composer.lock <-- important

@yyaremenko blindly recommending to remove composer.lock could lead to issues with other packages that get upgraded. Why not `composer require doctrine/migrations:^3.1.1`?

**Comment by yyaremenko** [comment] 2021-06-02 13:52
@stingus regarding composer.lock - yes, my bad, agree; regarding composer require - why should I require the library outside of bundle?

**Comment by stingus** [comment] 2021-06-02 13:57
@yyaremenko my bad this time :) I've meant `doctrine/doctrine-migrations-bundle:^3.1.1`. As of this moment, this should install `doctrine/migrations:3.1.2`.

**Comment by yyaremenko** [comment] 2021-06-02 14:10
@stingus the problem here is since the lock file has an older requirement, upon new version of bundle installation you get an error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/doctrine-migrations-bundle[3.1.0, ..., 3.1.x-dev] require doctrine/migrations ^3.1 -> found doctrine/migrations[3.1.0, ..., 3.2.x-dev] but the package is fixed to 3.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires doctrine/doctrine-migrations-bundle ^3.1 -> satisfiable by doctrine/doctrine-migrations-bundle[3.1.0, 3.1.1, 3.1.x-dev].
```

this can be fixed by running 
```
composer require doctrine/doctrine-migrations-bundle:^3.1.1 --with-dependencies
``` 
but this updates quite a lot of dependencies aside from doctrine migrations.
I'm not sure if this is okay?...

**Comment by yyaremenko** [comment] 2021-06-02 14:44
okay looks like I figured out the magic trick lol
```
composer update doctrine/migrations && composer require doctrine/doctrine-migrations-bundle:^3.1.1
```
looks like this one only updates the target library and the target bundle, leaving the rest of composer.lock intact.
If I'm doing it wrong, everybody is welcome to comment.

**Comment by NicoHaase** [comment] 2021-06-02 14:50
If you only want to update that bundle, why not run `composer update doctrine/doctrine-migrations-bundle`?

**Comment by yyaremenko** [comment] 2021-06-02 15:02
@NicoHaase good idea, thank you; but as I tried it, it updated the bundle from v3.0.2 to v3.0.3, and this is not what we want

**Comment by NicoHaase** [comment] 2021-06-02 15:25
What does `composer why-not doctrine/doctrine-migrations-bundle 3.1.2` tell you? Probably you need to update any other package too, but this is really out of scope for a bugtracker

**Comment by yyaremenko** [comment] 2021-06-02 15:45
> There is no installed package depending on "doctrine/doctrine-migrations-bundle" in versions not matching 3.1.2

(I've already updated to 3.1.1)

**Comment by ostrolucky** [comment] 2021-06-02 15:50
See linked issues and pull requests. I don't know why do you guys comment on closed issue...

**Comment by yyaremenko** [comment] 2021-06-02 16:15
@ostrolucky I wonder if you actually read the comments before making your remark. Because if you did, you would understand that 'linked issues and pull requests' had nothing to do with the problem discussed. Oh and probably you would also understand why we comment on a closed issue.

**Comment by nicwortel** [comment] 2021-06-04 07:50
I had also updated doctrine/migrations and doctrine/doctrine-migrations-bundle to their latest versions, but started to receive this error again. Turned out that it was caused by a `Connection` wrapper which isn't handled correctly by `Doctrine/Migrations/Tools/TransactionHelper.php`. See https://github.com/getsentry/sentry-symfony/issues/488, https://github.com/doctrine/migrations/pull/1149 and https://github.com/doctrine/dbal/issues/4616.

**Comment by ThibaultVlacich** [comment] 2021-07-10 23:49
@ostrolucky People are commenting on a closed issue because clearly, the issue is not fixed. I have doctrine/migrations 3.2.0 running on my project, and I am still getting the error 

```
[critical] Error thrown while running command "doctrine:migrations:migrate". Message: "There is no active transaction"


In TracingDriverConnection.php line 163:

  There is no active transaction
```

**Comment by RiseAndCry** [comment] 2021-10-20 10:22
Still having this issue with 2.3.4

**Comment by greg0ire** [comment] 2021-10-20 12:20
@RiseAndCry make sure you read https://www.doctrine-project.org/projects/doctrine-migrations/en/3.3/explanation/implicit-commits

**Comment by RiseAndCry** [comment] 2021-10-20 12:29
So i guess i should either add 'isTransactional()) methods to all migrations if using <3.0 version or use configuration to specify the same with >3.0 ? (at least these seem to be the simplest solutions)

Thanks for the link

**Comment by greg0ire** [comment] 2021-10-20 13:45
The configuration only affects new migrations, so you will have to do the first item regardless of the version. It would be cool if there was a way to do this with Rector

**Comment by povilas-oxylabs** [comment] 2021-10-20 13:46
ok, thanks.

**Comment by jerru11** [comment] 2021-10-21 13:38
Hi! The easiest solution is to provide needed version in composer.json

`   
     "doctrine/doctrine-migrations-bundle":"3.1.1",
      "doctrine/migrations": "3.2.1",
`
        
Transactions works correctly with php 8.0 + MySql 5.7

**Comment by RiseAndCry** [comment] 2021-10-21 13:40
I'd rather not upgrade to 3 yet, it's not perfect when using multiple entityManagers (at least i haven't found a good way to make it work yet). But your solution might work for others. Thanks either way.

**Comment by ivaskad** [comment] 2021-10-21 13:44
> "doctrine/doctrine-migrations-bundle":"3.1.1", "doctrine/migrations": "3.2.1

This works for me, 

downgrade `doctrine/doctrine-migrations-bundle` from `3.2.0` to `3.1.1`
and `doctrine/migrations` from `3.3.0` to `3.2.1`

on php8 & MySQL 8.0.20

**Comment by mariusjp** [comment] 2021-10-25 06:07
> > "doctrine/doctrine-migrations-bundle":"3.1.1", "doctrine/migrations": "3.2.1
> 
> This works for me,
> 
> downgrade `doctrine/doctrine-migrations-bundle` from `3.2.0` to `3.1.1` and `doctrine/migrations` from `3.3.0` to `3.2.1`
> 
> on php8 & MySQL 8.0.20

Same setup, can confirm, this works

**Comment by digitalkaoz** [comment] 2022-02-08 17:16
@greg0ire im getting this error too (without using doctrine migrations) by using doctrine/dbal and php8. any chance this fix might be ported to dbal too? i guess it wont be changed on the PHP-SRC side

**Comment by greg0ire** [comment] 2022-02-08 19:56
@digitalkaoz what fix? There is no fix, just don't attempt to use DDL + transactions with MySQL or Oracle, they do not support it.

**Comment by cavasinf** [comment] 2022-05-19 14:59
Following the doc : https://www.doctrine-project.org/projects/doctrine-migrations/en/3.3/reference/configuration.html
Disable globally `transactional` by setting it to `false` for migrations solve that case.

----------------

If you are using Symfony and `doctrine/doctrine-migrations-bundle` `3.2.x`, follow the doc : https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html
To disable `transactional` from `config/packages/doctrine_migrations.yaml`
