### ISSUE TITLE
Doctrine Migrations 3.0.0 Stable

### ISSUE THREAD

**Issue by bugalot** [doctrine/migrations#983] opened 2020-06-12 10:56 UTC
|    Q        |   A
|------------ | -----
| Version     | 3.0.0

### Support Question

Hello there!

First, thanks a lot for Doctrine Migrations. It's a wonderful tool. My team is currently working on a new feature based on Doctrine Migrations `3.0.0-beta1`. It works great. However, we would like to wait for a stable version before pushing this new feature in production.

Do you guys have a already an idea in terms of a release date for Doctrine Migrations `3.0.0` stable? 

I could see that the latest builds were about 20 days ago and it seems that this is because in previous builds, `doctrine/common (2.13.0)` was in use but in the latest ones, `doctrine/common (3.0.1)` which is causing some required classes to disappear. (you can compare [here](https://travis-ci.org/github/doctrine/migrations/builds/691070607) vs [here](https://travis-ci.com/github/oat-sa/migrations/builds/168931134))

Maybe we can help?

All the best and thank you again!

**Comment by goetas** [comment] 2020-06-12 11:30
The persistentce classes have been removed from the common lib in its own
package. If you need those classes you should install the persistentce
package

**Comment by bugalot** [comment] 2020-06-12 12:29
But why then are these classes still required in the latest builds (causing the errors)? Is it just a matter of including the persistence package in the doctrine/migrations composer file?

For my information, where is this package located?

**Comment by stof** [comment] 2020-06-12 13:00
The issue is that some test files are still using the old namespace for persistence classes: https://github.com/doctrine/migrations/blob/42f7c908ed8f35945ed0c6df9e971cf139ae6ed0/tests/Doctrine/Migrations/Tests/Configuration/EntityManager/_files/em-loader.php#L5

When doctrine/persistence 2.0 is installed, only the new namespace is available. Tests should not rely on deprecated class names of persistence 1.x

**Comment by greg0ire** [comment] 2020-06-12 19:25
I'm on it.

**Comment by greg0ire** [comment] 2020-06-12 19:31
Un-assigning myself since I'm unsure if this is solely about these build issues or if there are more things blocking the release.

**Comment by goetas** [comment] 2020-06-13 09:14
Since https://github.com/doctrine/migrations/pull/984 is merged, can we consider this as solved?

**Comment by bugalot** [comment] 2020-06-13 11:55
Awesome guys the build is passing again! 

Do you still have things to be done to reach the 3.0.0 stable milestone? Can we somehow help?

**Comment by bugalot** [comment] 2020-06-13 12:00
And to me, it looks to be solved of course :smile: ! Thanks again guys!

**Comment by goetas** [comment] 2020-06-13 12:56
Closing then :)

**Comment by goetas** [comment] 2020-06-13 12:56
> Do you still have things to be done to reach the 3.0.0 stable milestone? Can we somehow help?

Hopefully next week 3.0 will be tagged

**Closed by goetas** 2020-06-13 12:56 UTC

**Comment by bugalot** [comment] 2020-06-13 13:14
It would be wonderful @goetas
