### ISSUE TITLE
[PDOException (IMSSP)] SQLSTATE[IMSSP]: This function is not implemented by this driver.  

### ISSUE THREAD

**Issue by S-Tian86** [doctrine/migrations#1217] opened 2021-11-25 11:47 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.3.2

#### Summary
I Used php 8 on IIS with SQL Server whith the driver pdo_sqlsrv 5.9

When I run a migration I get the error
```
In TransactionHelper.php line 63:
  [PDOException (IMSSP)]                                             
  SQLSTATE[IMSSP]: This function is not implemented by this driver.  

Exception trace:
  at C:\Users\...\vendor\doctrine\migrations\lib\Doctrine\Migrations\Tools\TransactionHelper.php:63
 method_exists() at C:\Users\...\vendor\doctrine\migrations\lib\Doctrine\Migrations\Tools\TransactionHelper.php:63
```
https://github.com/doctrine/migrations/blob/3ec95c4baf9ce66f86147d845f82941131d785f6/lib/Doctrine/Migrations/Tools/TransactionHelper.php#L60-L70

#### Current behavior

Migration does not run.

I debugged the error and realized the following:
On line 63, in the first iteration, when it enter the while, the class type of `$innermostConnection` is `Doctrine\DBAL\Connection` 
After that line 64 is executed, the class type of `$innermostConnection` is `Doctrine\DBAL\Driver\PDO\SQLSrv\Connection` and it re-evaluates the while condition. As the condition is correct, it re-enters a second time.
In the next iteration, after that line 64 is executed, the class type of `$innermostConnection` change to `PDO`
And when it re-evaluates `method_exists()` on line 63 on an object of type `PDO`, the exception is thrown.

#### How to reproduce

I'm sorry, but I don't really know how to reproduce it, I guess by doing a migration and running it.

#### Expected behavior

I changed line 63 and it worked without problems. What I don't know if that breaks anything else in the rest of the code.
```php
    private static function inTransaction(Connection $connection): bool
    {
        $innermostConnection = $connection;
        while (! $innermostConnection instanceof PDO && method_exists($innermostConnection, 'getWrappedConnection')) {
            $innermostConnection = $innermostConnection->getWrappedConnection();
        }

        /* Attempt to commit or rollback while no transaction is running
           results in an exception since PHP 8 + pdo_mysql combination */
        return ! $innermostConnection instanceof PDO || $innermostConnection->inTransaction();
    }
```
Regards.

**Comment by greg0ire** [comment] 2021-11-25 13:32
Duplicate of https://github.com/doctrine/migrations/issues/1214

**Closed as completed by greg0ire** 2021-11-25 13:32 UTC
