### ISSUE TITLE
Diff-generated migration contains CREATE SCHEMA in down()

### ISSUE THREAD

**Issue by vbence** [doctrine/migrations#220] opened 2015-03-10 10:44 UTC
My generated migrations all start with the following line in the `down()` method, including the very first and all subsequent versions. If I remove it by hand they work fine.

I`m using postgresql; I'm on version 93a9369ea7846e8ae2e9303c94bb36dbcbb2009b of migrations.

```
    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
```

**Comment by mikeSimonson** [comment] 2015-03-10 22:58
Did you generated them using the diff command ?
If so the problem is in the doctrine orm and you should make the bug report there.

**Comment by vbence** [comment] 2015-03-11 08:24
Yes, thanks, it is already there in the output of Schema#getMigrateFromSql

**Comment by stof** [comment] 2015-03-11 10:15
Closing in favor of http://www.doctrine-project.org/jira/browse/DBAL-1168

**Closed by stof** 2015-03-11 10:15 UTC
