### ISSUE TITLE
Feature Request:  Add timestamp to migration table

### ISSUE THREAD

**Issue by wshafer** [doctrine/migrations#459] opened 2016-05-09 21:50 UTC
Hey Guys,

Quick feature request. It would be nice to know when a particular migration ran. A time stamp added to the versions table would be nice.

Use Case: We had a migration that ran which deleted a needed column for reporting. Unfortunately I don't know when the migration actually ran to try and recover the data from backups.

Thanks in advance,
Westin

**Comment by JHGitty** [comment] 2016-05-09 21:55
:+1: +1

**Comment by kilhage** [comment] 2016-05-17 12:03
:+1:

**Comment by stof** [comment] 2016-05-17 13:06
Duplicate of https://github.com/doctrine/migrations/issues/331

**Closed by stof** 2016-05-17 13:06 UTC
Labels: new feature
