### ISSUE TITLE
Remove PHP 7.4 from `allow_failures`

### ISSUE THREAD

**Issue by carusogabriel** [doctrine/migrations#861] opened 2019-10-01 07:54 UTC
PHP 7.4 will be released [soon](https://wiki.php.net/todo/php74) and we need to ensure that `Doctrine` is compatible with it.

All we need to do is to remove these following lines

https://github.com/doctrine/migrations/blob/50c7d160c249b9acbc25090a6a8eb2ee8f66e959/.travis.yml#L26-L27

 and verify that everything is working.

This is a very good issue for those who want to participate in https://hacktoberfest.digitalocean.com.

**Comment by WilChrist** [comment] 2019-10-01 08:37
I Can handle this.

**Comment by greg0ire** [comment] 2019-10-01 19:44
@WilChrist you can have a look at the Travis build: https://travis-ci.org/doctrine/migrations/builds/592060520?utm_source=github_status&utm_medium=notification (right now it's not working, sorry)

**Comment by WilChrist** [comment] 2019-10-03 08:16
yes @greg0ire but the errors seems to be in the test, caused by deprecated functions ? should i replace them by currently used functions ?

**Comment by greg0ire** [comment] 2019-10-03 09:51
Yes, absolutely, please do that!

**Comment by WilChrist** [comment] 2019-10-03 10:16
@greg0ire how could i test localy if it work ?

**Comment by greg0ire** [comment] 2019-10-03 13:14
You can try running `./vendor/bin/phpunit`. You will find more information about how to contribute here: https://www.doctrine-project.org/contribute/index.html

**Comment by goetas** [comment] 2019-12-01 09:14
Fixed in https://github.com/doctrine/migrations/pull/869

**Closed by goetas** 2019-12-01 09:14 UTC
Labels: CI, Hacktoberfest
