### ISSUE TITLE
Error : The path "/tmp/migration.sql" not writeable!

### ISSUE THREAD

**Issue by Webonaute** [doctrine/migrations#1162] opened 2021-05-25 19:27 UTC
running 
```
bin/console doctrine:migration:migrate --write-sql=/tmp/migration.sql --dry-run -vvv
```

generating error :
```
[ERROR] The path "/tmp/migration.sql" not writeable!
```

using _is_writable_ in the command return false if the file does not exist.
is it intentional to force the file to exist?

The workaround is to perform a touch on the file before run the script.

**Comment by greg0ire** [comment] 2021-05-25 19:57
Isn't `--write-sql` supposed to be a directory? The default value seems to be. If yes, consider contributing a check.

**Comment by Webonaute** [comment] 2021-05-25 20:06
you are right, if I put /tmp. it create a file like /tmp/doctrine_migration_20210525200024.sql
but if I do touch /tmp/migration.sql; bin/console doctrine:migration:migrate --write-sql=/tmp/migration.sql --dry-run -vvv it create my /tmp/migration.sql correctly. and I actually need to specify the sql file name to execute my full migration procedure.

so I think it missing a check if the path contain .sql to check the permission on parent directory instead.

**Comment by greg0ire** [comment] 2021-06-19 13:50
:thinking: so if the path exists and is a file, it fills, it, if it's a directory it creates a file, and if it does not exist, we get a crash, huh? Kind of weird indeed.

Maybe `doctrine/migrations` is being pedantic here: since it's valid to have a directory named `file.sql`, and it's equally valid to have a file named `directory`, it's impossible to tell what's the intended behavior. This could be fixed by saying that if the path does not exist but its parent directory does, we `touch` that path. Would you be willing to contribute that? We would assume that no one would run `--write-sql=path/to/directory/that/does/not/exist` and expect a file to be created in there.

**Comment by goetas** [comment] 2021-07-27 14:01
see https://github.com/doctrine/migrations/pull/1187

**Comment by Webonaute** [comment] 2021-07-27 15:21
yeah seem good

**Closed as completed** 2021-08-03 11:49 UTC
